version: '3.8'
services:
  app:
    build:
      context: .
      args:
        IMAGE_TAG: ${IMAGE_TAG:-latest}
    image: 'agencerevontuli/lukeeapp:${IMAGE_TAG}'
    ports:
      - '3333:3333'
    environment:
      PORT: ${PORT}
      HOST: ${HOST}
      NODE_ENV: ${NODE_ENV}
      APP_KEY: ${APP_KEY}
      DRIVE_DISK: ${DRIVE_DISK}
      SESSION_DRIVER: ${SESSION_DRIVER}
      CACHE_VIEWS: ${CACHE_VIEWS}
      DB_CONNECTION: ${DB_CONNECTION}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB_NAME: ${PG_DB_NAME}
      LOG_LEVEL: ${LOG_LEVEL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LINKEDIN_CLIENT_ID: ${LINKEDIN_CLIENT_ID}
      LINKEDIN_CLIENT_SECRET: ${LINKEDIN_CLIENT_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      APP_URL: ${APP_URL}
    volumes:
      - .:/app
    command: node build/server.js
